### PR TITLE
num num num

### PR DESCRIPTION
**Pull request by RobertASmith**
BD

### CODE REVIEW

**Comment by DKBurns** [comment]
🤦‍♂️

**Comment by RobertASmith** [comment]
Googled this, looks amazing: 
image

**Comment by DKBurns** [comment]
`((13.95+42)/2) + (3.50/3) = 29.14167` - I'll send 30!

**Comment by DKBurns** [comment]
sent

**Comment by DKBurns** [comment]
> Googled this, looks amazing: image

It's really fun and a bit cold. The sea right next to it is free though, so that's where I usually go!

**Comment by RobertASmith** [comment]
I'll pay you back  85.833 pence one day, I promise!

This is the nerdiest bill split ever!

**Comment by DKBurns** [comment]
oh @RobertASmith don't forget to edit your bank deets out of the comment 🤣

**Pull request closed without merging**
